- name: Create infrastructure stack
  hosts: infraserver
  gather_facts: yes
  vars:
    deploy_user: deploy
    ssh_port: 22
    maintenance_email: "contact.louisemard@icloud.com"

    infisical_domain: "vault.louisemard.dev"
    infisical_dir: "/opt/infisical"

  become: yes

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Install nginx for reverse proxy
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Start nginx and enable at boot
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
    - name: Install Docker
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
        state: present
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Start docker service and enable at boot
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    - name: Add deploy user to docker group
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        groups: docker
        append: yes
    # Reset SSH connection to apply docker group
    - name: Reset SSH connection to apply docker group
      meta: reset_connection
    # Installation de certbot pour les certificats SSL
    # On l'installe ici car on en aura besoin pour les différents services (infisical, gitea, etc.)
    - name: Install Certbot
      apt:
        name: 
          - certbot
          - python3-certbot-nginx
        state: present
    # Import gitea tasks
- import_playbook: gitea.yaml
- import_playbook: infisical.yaml