export INFISICAL_DB_PASSWORD=$(openssl rand -base64 32)
# Hex 16 from infisical docs
export INFISICAL_ENCRYPTION_KEY=$(openssl rand -hex 16)
export INFISICAL_AUTH_SECRET=$(openssl rand -hex 16)

export INFISICAL_ADMIN_EMAIL="emard.louis@icloud.com"
export INFISICAL_ADMIN_PASSWORD=$(openssl rand -base64 32)

echo "Secrets générés:"
echo "INFISICAL_DB_PASSWORD=${INFISICAL_DB_PASSWORD}"
echo "INFISICAL_ENCRYPTION_KEY=${INFISICAL_ENCRYPTION_KEY}"
echo "INFISICAL_AUTH_SECRET=${INFISICAL_AUTH_SECRET}"
echo "INFISICAL_ADMIN_PASSWORD=${INFISICAL_ADMIN_PASSWORD}"

# Write variables to secrets file
cat > infisical_secrets.env << EOF
INFISICAL_DB_PASSWORD=${INFISICAL_DB_PASSWORD}
INFISICAL_ENCRYPTION_KEY=${INFISICAL_ENCRYPTION_KEY}
INFISICAL_AUTH_SECRET=${INFISICAL_AUTH_SECRET}
INFISICAL_ADMIN_PASSWORD=${INFISICAL_ADMIN_PASSWORD}
EOF